# Generated by Django 5.2.7 on 2025-11-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickMgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='stats',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='gatos_pulsados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='mejoras',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stats',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='puntaje_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickMgr.player'),
        ),
    ]
